In [20]:
import numpy as np

In [21]:
lst=[1,2,3,4,5,6]
arr=np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [22]:
arr.shape

(6,)

In [26]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])
print(arr1)
arr1.shape



[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


(3, 5)

In [31]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [37]:
np.arange(1,21,1).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [40]:
print(arr1)
arr1*2

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [49]:
print(np.ones((2,10)))
print(np.zeros((2,10,2)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [56]:
np.random.randint(1,10,10)

array([1, 3, 8, 6, 7, 2, 1, 3, 5, 1], dtype=int32)

In [ ]:
x=np.random.normal(0,1,10)
y=np.arange(1,6)

array([ 1.80386368,  0.44154309,  0.07004037, -0.9227978 ,  0.95733537,
       -0.62558544, -0.60599423,  0.37333629,  0.04381008,  0.47661557])

In [82]:
import matplotlib.pyplot as plt